name: Docker Image Build & Push

on:
  push:
    branches:
      - main
    paths:
      - 'backend-services/**'
      - 'frontend-user-management/**'
  pull_request:
    branches:
      - main

jobs:
  # --- Backend Go Services ---
  build-go-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, services/store-management, services/product-catalog, services/order-management]
    if: contains(github.event.head_commit.message, matrix.service) || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Go Service
        run: |
          cd backend-services/${{ matrix.service }}
          go mod tidy
          go test ./...
          go build -o app ./cmd/main.go

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ./backend-services/${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest

  # --- Frontend (Next.js) ---
  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'frontend-user-management')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install & Build
        run: |
          cd frontend-user-management
          npm install
          npm run build

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-user-management
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user-management:latest